// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVl7EJeO-mZFWQBYUb7xRJY3EhZWragWM',
    appId: '1:181907846295:web:8564240bf05bf8e26125d2',
    messagingSenderId: '181907846295',
    projectId: 'food-app-275f4',
    authDomain: 'food-app-275f4.firebaseapp.com',
    storageBucket: 'food-app-275f4.firebasestorage.app',
    measurementId: 'G-26BSFDHRTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_1XT7PTJ8HMPp61XQ35wTlZktTuwTJNo',
    appId: '1:181907846295:android:e7094c03399805e36125d2',
    messagingSenderId: '181907846295',
    projectId: 'food-app-275f4',
    storageBucket: 'food-app-275f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFZNyTRDkiMWUiopZ14lR9XbNNnVQ4NTQ',
    appId: '1:181907846295:ios:6f9501c9762d11246125d2',
    messagingSenderId: '181907846295',
    projectId: 'food-app-275f4',
    storageBucket: 'food-app-275f4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFZNyTRDkiMWUiopZ14lR9XbNNnVQ4NTQ',
    appId: '1:181907846295:ios:6f9501c9762d11246125d2',
    messagingSenderId: '181907846295',
    projectId: 'food-app-275f4',
    storageBucket: 'food-app-275f4.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVl7EJeO-mZFWQBYUb7xRJY3EhZWragWM',
    appId: '1:181907846295:web:f302b00708cdc7ee6125d2',
    messagingSenderId: '181907846295',
    projectId: 'food-app-275f4',
    authDomain: 'food-app-275f4.firebaseapp.com',
    storageBucket: 'food-app-275f4.firebasestorage.app',
    measurementId: 'G-2GR3DFV62F',
  );
}
